### ISSUE TITLE
Neither `sos-notebook` nor `jupyterlab-sos` works...

### ISSUE THREAD

**Issue by AnselmJeong** [vatlab/sos-notebook#330] opened 2021-09-22 08:52 UTC
I found this project today, and I tried to make it work.
However, whenever I tried to change kernel, this error message pops up and the notebook just hangs indefinitely.

![image](https://user-images.githubusercontent.com/1776524/134311632-658b0554-5f4a-46e1-90bf-126c6456da0c.png)

I did not issue a complicated command, just see below.

![image](https://user-images.githubusercontent.com/1776524/134311789-5d528123-e545-481c-88c5-cb98bc54b77e.png)

I even installed all the newest related modules directly from github, but it doesn't work either....

`jupyter kernelspec list` correctly shows the needed kernels.

![image](https://user-images.githubusercontent.com/1776524/134312236-bd733d64-1b14-4e85-8ab7-349042a0c350.png)

I've tried `sos-notebook` but failed to make it work either.

Does any one use this exceptional package in their work recently or just abandoned nowadays?

Thanks.

**Comment by BoPeng** [comment] 2021-09-22 21:36
Not sure about the first one, but the 2nd one is #328 and currently the best approach is to downgrade jupyter_client to 6.x.x. This is not a problem that affects many kernels, not just sos notebook.

**Comment by BoPeng** [comment] 2021-09-23 20:35
@AnselmJeong Could you try the async branch of sos-notebook and see if it works for you? Thanks.

**Comment by BoPeng** [comment] 2021-09-23 21:56
I have released sos-notebook 0.22.7. Please let me know if the problem persists.

**Comment by AnselmJeong** [comment] 2021-09-24 12:14
It works beautifully..... Thanks for your hard work.

But there is one issue that has not been solved.....

The `jupyter` log window spawned out these warning messages....

![image](https://user-images.githubusercontent.com/1776524/134672241-42fdbb08-54db-4a37-ac9e-197521a6426b.png)

May be spelling mistakes?

from AnselmJeong

**Comment by AnselmJeong** [comment] 2021-09-24 13:06
Another question...

Can't `julia` kernel get a dataframe made in `R` kernel?

In my experimentation, `julia` kernel can get a vector and a list from `R` kernel without a problem. But it fails to get any dataframes.

In contrast, `SoS` kernel can any type of data from `R` kernel.
`Julia` kernel cannot get a dataframe imported into `SoS` kernel.
This problem also applies to tibble format.

The following is my experimentation.

![image](https://user-images.githubusercontent.com/1776524/134678937-093d99f1-9dbc-4f89-af6e-9ea44a7ff92b.png)

**Comment by BoPeng** [comment] 2021-09-24 16:31
I have transferred the issue to https://github.com/vatlab/sos-julia/issues/23

**Comment by BoPeng** [comment] 2021-09-24 16:34
@AnselmJeong The `template_path` issue is unrelated to sos-notebook. It was caused by the update of nbconvert which cuases a conflict with another package.

See https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1529 for more details.

**Closed** 2021-11-02 18:43 UTC
