### ISSUE TITLE
`nbconvert` does not work with SoS notebook `--execute` some kernels

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#112] opened 2018-08-18 13:39 UTC
To reproduce:

1. Create a new SoS notebook
2. In a cell select `R` kernel, paste in the codes below:

```r
g = 4.74
N = 1000
q = 0.1336
foo = function(x) N * (q-1-g*q+g) * x^2 - (N*q-N-N*q*g+g-1) * x - 1
p0 = uniroot(foo, lower=0, upper=1, tol = .Machine$double.eps^0.8)$root
p1 = g * p0 / (1-p0+g*p0)
print(c(p0,p1))
```

3. save it to `test.ipynb`, and run:

```
jupyter nbconvert test.ipynb --execute test.ipynb --output out.ipynb
```

Error message:

```
ParsingError: File contains parsing errors: 
	[line  2]: g = 4.74
N = 1000
q = 0.1336
foo = function(x) N * (q-1-g*q+g) * x^2 - (N*q-N-N*q*g+g-1) * x - 1
p0 = uniroot(foo, lower=0, upper=1, tol = .Machine$double.eps^0.8)$root

Invalid statements: SyntaxError('invalid syntax', ('<string>', 4, 19, 'foo = function(x) N * (q-1-g*q+g) * x^2 - (N*q-N-N*q*g+g-1) * x - 1\n'))

```

**Comment by BoPeng** [comment] 2018-08-18 13:54
I know this problem. The key for this functionality is to pass the right meta information to cells (e.g. cell kernel, embedded workflow etc), which basically means we need to translate relevant JS code in frontend into Python and use it to prepare the right metadata for [an batch mode executor](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/converter.py#L161) . `nbconvert --execute` worked when sos notebook was relatively simple but I have [disabled option `--execute`](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/converter.py#L132) after I realized that it is a lot of work to keep this rarely used feature up to date with the progress of sos notebook.

If we are to restore this feature, we will have to make sure it works exactly as in notebook, and use a different option, in line of

```
sos run filename.ipynb -e
```
to `execute` the notebook as a notebook, not as a workflow.

**Comment by BoPeng** [comment] 2018-08-27 05:57
`sos convert notebook.ipynb notebook.html --execute` has been added and needs further testing.

**Comment by BoPeng** [comment] 2018-08-27 17:07
I have submitted a ticket to nbconvert (https://github.com/jupyter/nbconvert/issues/865), trying to figure out if it is possible to use a customized preprocessor with option `--execute`.

**Comment by BoPeng** [comment] 2018-08-27 21:07
OK, it appears that `jupyter nbconvert --execute` would not work for sos notebook, so `sos convert sos.ipynb sos.html --execute` is the only option. Will you welcome an option for `sos run`? Something like `sos run sos.ipynb -e` for `as notebook`?

**Comment by gaow** [comment] 2018-08-27 21:16
`sos convert sos.ipynb sos.html --execute` looks good enough -- why do we need an option for `sos run`? I believe a conventionally user case would be `sos convert sos.ipynb sos_with_results.ipynb --execute`, that is, they want to get a version of SoS Notebook that has results in it. In fact as you've probably noticed `jupyter nbconvert --execute` will create a notebook called `xxx.nbconvert.ipynb`. So it is after all, a conversion. It would be awkward that `sos run` produce some new notebooks with `-e` used.

**Comment by BoPeng** [comment] 2018-08-27 21:28
There has been discussions on this because `--execute` is not conversion and `--inplace` is available to update a notebook with its executed version.

I think `sos convert sos.ipynb sos.html --execute` is good enough although `sos convert notebook.ipynb notebook.ipynb --execute` might not work, and there could be an option for `sos convert notebook.ipynb --execute --inplace` for refreshing a notebook.

Note that a few magics (#119) will not work in batch mode so at this point `--execute` needs more testing.

**Comment by gaow** [comment] 2018-08-28 23:06
It still does not work as expected:

![2018-08-28-18-05-16_scrot](https://user-images.githubusercontent.com/917985/44755730-f0937700-aaec-11e8-8398-fe7c05a156ed.png)


then:

```
[GW] sos convert test.ipynb /tmp/1.html --execute
[NbConvertApp] Converting notebook /home/gaow/tmp/test.ipynb to html
[NbConvertApp] Executing notebook with kernel: sos
[NbConvertApp] ERROR | Error while converting '/home/gaow/tmp/test.ipynb'
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 393, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 174, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 192, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/html.py", line 85, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 280, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 134, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 311, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 262, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/opt/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 288, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, reply['content'])
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
source('test_utils.R')
hi()
------------------


RuntimeError: 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
script_6604898368695140288 in <module>
----> source('test_utils.R')
      hi()

NameError: name 'source' is not defined

ERROR: Failed to convert test.ipynb to html format
[GW] 

```

**Comment by BoPeng** [comment] 2018-08-29 03:13
I cannot reproduce, did you use the master? Anyway, the feature was implemented in brach `nbconvert` and I just merged it to the trunk.

**Comment by BoPeng** [comment] 2019-07-25 04:41
There are two ways to implement command line execution of notebooks. The first one is using `nbconvert` and use a preprocessor to process cells. The problem with this approach is that the preprocessor need to be tested for various frontend-related functions. It should in theory work, but it is difficult to maintain and it may fail in complex cases.

The other method is to use selenium to mimic `Run all cells`. Basically we start a browser in the background and execute the notebook in the browser. This will require users to install `selenium` and a browser engine, but once it is done, we should have some confidence that as long as the notebook runs correctly in a browser, it should run correctly in this hidden browser.

I tend to think we should replace the existing `nbconvert` approach with an `selenium` approach.

**Comment by BoPeng** [comment] 2019-07-25 04:51
The bottomline is that we should test the `--execute` option more aggressively and fix bugs along the way, and try to `selenium` approach if fixing bugs becomes.

**Comment by gaow** [comment] 2019-07-25 05:35
It was a need I had earlier but I think for that particular project I was trying to convert some Rmd files to SoS Notebook. Of course after conversion there is no output in the notebook and that is why I needed to execute. I think I ended up converting Rmd to a regular Jupyter Notebook, due to this constraint. I am bringing this up as one additional user case to consider when designing improved Rmd to SoS Notebook converter.

**Comment by BoPeng** [comment] 2019-07-25 12:37
If I recall correctly, the biggest problem with the current `--execute` approach is JS and `comm` related features. For example, there is no support for `%preview -n` or `%preview -s` because without a real frontend, there is no way to simulate the existence of console panel. There is also no way to support `%preview --workflow` because it is implemented by inserting a cell through the comm channel.

The root of the problem is that SoS Notebook played too much tricks using JS and customized comm so there is no way to reliably reproduce a SoS Notebook without a proper frontend, so a `selenium`-based approach seems to be the only feasible way. I guess additional installation trouble (chrome driver) is something we can tolerate.

**Closed** 2020-01-08 15:10 UTC
Labels: discussion, enhancement, request, soon
