### ISSUE TITLE
Data exchange bug with numpy

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#20] opened 2017-11-28 17:44 UTC
MWE:

![2017-11-28-11-43-13_scrot](https://user-images.githubusercontent.com/917985/33335016-69da0c34-d431-11e7-98a1-8e98b8ff628b.png)

The data lost dimension info after loaded to R

**Comment by gaow** [comment] 2017-11-28 17:47
BTW if I use `np.matrix` the exchange is fine. But the problem is that even for a true matrix I do often still use `np.array` not `np.matrix` because `np.array` gives me more flexibility in what to do with the matrix other than standard matrix algebra. eg, `np.array` is more convenient for things such as multiplying each row of a matrix by another vector.

**Comment by BoPeng** [comment] 2017-11-28 17:53
Duplicate of https://github.com/vatlab/sos-r/issues/1 @HenryLeongStat  is working on it.

**Closed by BoPeng** 2017-11-28 17:53 UTC
