### ISSUE TITLE
Current pip versions (sos=0.18.4 and sos-notebook=0.18.3) results in Jupyter kernel hanging then crashing

### ISSUE THREAD

**Issue by mathieuboudreau** [vatlab/sos-notebook#188] opened 2019-01-30 19:29 UTC
Docker file: https://github.com/qMRLab/t1_notebooks/blob/sos0.18.4_sosnotebook0.18.3/Dockerfile

MyBinder environment to a Jupyter Notebook using that setup: https://mybinder.org/v2/gh/qMRLab/t1_notebooks/sos0.18.4_sosnotebook0.18.3?filepath=vfa_blog%2FVariableFlipAngle.ipynb

Kernel icon stays on "Connecting to kernel..." and then crashes (Connection failed popup). =(

Any idea why, and I could get a working setup in the short term? I used to be using sos==0.17.7 and sos-notebook==0.17.2. However, today to create a new environment (I was used saved Docker images for the past month or so) with those settings I got this error in the left panel.

```

WARNING: Failed to locate subkernel Octave with kernerl "octave" and language "Octave": (sos-notebook 0.17.2 (/opt/conda/lib/python3.6/site-packages), Requirement.parse('sos-notebook>=0.18.0'))
WARNING: Failed to locate subkernel Python3 with kernerl "python3" and language "Python3": (sos-notebook 0.17.2 (/opt/conda/lib/python3.6/site-packages), Requirement.parse('sos-notebook>=0.18.1'))
WARNING: Failed to locate subkernel Octave with kernerl "octave" and language "Octave": (sos-notebook 0.17.2 (/opt/conda/lib/python3.6/site-packages), Requirement.parse('sos-notebook>=0.18.0'))
WARNING: Failed to locate subkernel Python3 with kernerl "python3" and language "Python3": (sos-notebook 0.17.2 (/opt/conda/lib/python3.6/site-packages), Requirement.parse('sos-notebook>=0.18.1'))

```

It's a bit annoying that I can't fix the sos versions to older working versions permanently - why do you have it set up this way? Is it because the most up-to-date language+sos kernels get installed to the most up-to-date versions whenever when installing any version "sos"? Anyway I can fix these versions to older ones?

<img width="1440" alt="capture d ecran 2019-01-30 a 15 49 53" src="https://user-images.githubusercontent.com/1421029/52006442-b74da180-24a6-11e9-9cce-e1fbfd4a3572.png">

Docker files: https://github.com/qMRLab/t1_notebooks/blob/blog_mp2rage/Dockerfile

It would be really nice if there was a stable way of setting working versions; I know you are always developing new features, but the option for users to install older working versions and would be great.

**Comment by mathieuboudreau** [comment] 2019-01-30 19:50
Related to my last point: I was just able to get it working by installing the previous versions for all the notebook kernels *after* `sos` is installed:

https://github.com/qMRLab/t1_notebooks/blob/52cd6aa55c9cac25e9b6df5747ea0bddbdaba3a5/Dockerfile#L43-L53

Working Jupyter Notebook setup in a MyBinder environment: https://mybinder.org/v2/gh/qMRLab/t1_notebooks/blog_mp2rage?filepath=mp2rage_blog%2FMP2RAGE.ipynb

**Comment by BoPeng** [comment] 2019-01-30 20:44
I am sorry for the troubles. In theory, if you upgrade `sos` and/or `sos-notebook`, they may require supporting module to be upgraded as well, and it should be relatively easy to upgrade these modules (`pip install sos-r -U` etc). I used to cross-reference `sos-notebook` with these language modules so that the language modules could be upgraded automatically but it was a disaster for distribution (e.g. when the packages are managed by conda) so I stopped doing that.

If you are using Docker, a good practice is indeed to use fixed known-to-be-working versions so that the docker image will not be affected by upstream version changes. The crash is a bit concerning though, did you get the crash with all recent versions of `sos`, `sos-notebook`, and the language modules?

**Comment by BoPeng** [comment] 2019-01-30 20:57
You will need to add `sos-matlab` etc to your [previous version of Dockerfile](https://github.com/qMRLab/t1_notebooks/blob/sos0.18.4_sosnotebook0.18.3/Dockerfile), and it should work without version because the newest versions will be installed. As I have explained, previous 

```
pip install sos-notebook
```
automatically installs `sos-r` etc. However, because `sos-r` depends on `sos-notebook`, allowing `sos-notebook` to depend on `sos-r` creates circular dependency that irritates `conda` so I had to remove them.

I am checking why sos kernel fails to start though.

**Comment by BoPeng** [comment] 2019-01-30 21:35
It is confirmed that your original docker image would work with the addition of

```
                sos \
                sos-notebook \
                sos-matlab \
                sos-python \
                matplotlib \
```
`matplotlib` needs to be specified separately because it should be a dependency of an upstream package but we might add it back since we have no control over the dependency of other packages.

**Closed by BoPeng** 2019-01-30 21:35 UTC

**Comment by mathieuboudreau** [comment] 2019-01-31 00:17
Thanks a lot for clarifying all these things - I will test the new setup soon!

>You will need to add sos-matlab etc to your previous version of Dockerfile

That would not have been obvious to me, since I did not have to before. I guess I just got used to the old setup!

>I am sorry for the troubles.

No need to apologize - take it as a compliment; your tool is that useful that I depend on it so much! =)

**Comment by mathieuboudreau** [comment] 2019-01-31 01:16
So the new installation instructions work - thanks for that!

However, the new HTML output format doesn't fit my need anymore - the Plotly figures don't display, and the side panel and drop down menu are too much (not clean for my application). Any way to output the old HTML format in the newer version of SoS (no panel, and the top left cursor hover for the "Show all cells" etc options)? 

If not that's fine, I'll just stick on the older SoS versions. I use the HTML outputs to embed them in a blogs with iframes, see here (scroll down): https://qmrlab.org/jekyll/2018/12/11/T1-mapping-variable-flip-angle.html

**Comment by BoPeng** [comment] 2019-01-31 01:33
Nice looking blog!

Well, a user complaint that the control panel was hidden too well and people could not open it even with explicit instruction. This agreed more or less with what we experienced so we changed it to a new button to the top right corner of the page.

If you are more or less ok with the drop down menu, you can use

```
sos convert my.ipynb my.html --template sos-report
```
which is the version without TOC and with the control panel. You will have to provide your own template if you want to, for example, hide the dropdown menu. Basically, you will need to define a file, say, `mytemplate.tpl` with content

```
{% extends 'sos-report.tpl' %}

{% block html_head %}
{{ super() }}
<style type="text/css">
#display_toggle_dropdown  {
display: none;
}

</style>
{% endblock html_head %}
```

and run
```
sos convert my.ipynb my.html --template mytemplate.tpl
```

You can of course try to use the [old version of the control panel](https://github.com/vatlab/sos-notebook/blob/5b78496846b48f9ee6a20efc1e35752d17207fdd/src/sos_notebook/templates/parts/control_panel.tpl) and [sos-report.tpl](https://github.com/vatlab/sos-notebook/blob/5b78496846b48f9ee6a20efc1e35752d17207fdd/src/sos_notebook/templates/sos-report.tpl) if you prefer.

**Comment by BoPeng** [comment] 2019-01-31 01:36
BTW, your trick of using inline css should also work.

```
display(HTML(
    '<style type="text/css">'
    '.output_subarea {'
       
```

**Comment by mathieuboudreau** [comment] 2019-02-01 01:35
Oh wow - thank you so much @BoPeng !! Thanks for spending time helping me.
